services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibkr_bot
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Exposes the Quart API on port 5000

  ngrok:
    build:
      context: ./ngrok
    container_name: ngrok
    depends_on:
      - bot
    ports:
      - "4040:4040"  # Exposes ngrok web interface on port 4040
    command: ngrok http --domain=hound-finer-mite.ngrok-free.app bot:5000
